spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/spring_batch
    username: root
    password: root
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}
  sql:
    init:
      platform: mysql
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
